### ISSUE TITLE
Errors with small datasets

### ISSUE THREAD

**Issue by LauRich05** [carmonalab/STACAS#10]
Hi there, 

Have you ever encountered issues with integrating datasets that contains some samples with small cell numbers (<500)? I am applying STACAS to a dataset like this, and keep running into the following error during the IntegrateData() step:

`Error in idx[i, ] <- res[[i]][[1]] :
  number of items to replace is not a multiple of replacement length
Calls: IntegrateData ... FindWeights -> NNHelper -> do.call -> AnnoyNN -> AnnoySearch
Execution halted`

Some seurat forums have suggested reducing the k.weight parameter to oversome this error. I have tried increments of 5 for k.weight values between 100 (default) to 5 with no success. Similarly, I do not get this error on the same dataset when performing RPCA integration with Seurat which uses the IntegrateData() function.

Do you have any advice on how to overcome this issue? Perhaps in some of the steps upstream of IntegrateData(). 

Thank you!

Laura

**Comment by mass-a** [comment]
Hello,
you could check how many anchors were left after anchor filtering:
```
ref.anchors.filtered <- FilterAnchors.STACAS(ref.anchors)
table(ref.anchors.filtered@anchors[,c("dataset1","dataset2")])
```
It's possible that, after filtering, for some of your datasets you have too few anchors left to perform integration (seeing that you are already starting with very few cells). If that is the case, you could try lower the `dist.thr` parameter in `FilterAnchors.STACAS` until you have enough anchors to perform integration. You may have to combine that with a lower `k.weight`, as you already do.

Let us know if that works!
