### ISSUE TITLE
package installation suddenly stopped working

### ISSUE THREAD

**Issue by alexthiery** [carmonalab/STACAS#13]
Hi,

I have been regularly building Docker images with STACAS installed, however it has just started to throw the error below (which has never happened previously).

The installation was attempted using the following command:

```r
remotes::install_github('carmonalab/STACAS')
```

Error:

```
Error: Failed to install 'STACAS' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr:
E> * checking for file ‘/private/var/folders/pg/nxjtjhms3k55ll9nb3wmpfnm0000gn/T/RtmpqtJBGm/remotes32eb7dd6b0ec/carmonalab-STACAS-f535645/DESCRIPTION’ ... OK
E> cp: carmonalab-STACAS-f535645/docs/index.html: No such file or directory
E>  ERROR
E> copying to build directory failed
```

The installation works when building from 1.1.0

```r
remotes::install_github('carmonalab/STACAS@1.1.0')
```

For now I will use one of the previous tagged versions, but I thought I would raise this incase anyone else is having the same issue.

Thanks,
Alex

**Comment by mass-a** [comment]
Hello Alex,
thanks for reporting this. Indeed there was a broken symlink left behind from the latest update, which I have now removed. Installation should be working again, otherwise let us know.

Cheers,
-m
