### ISSUE TITLE
file and link not accessible

### ISSUE THREAD

**Issue by MingwuDuan** [carmonalab/STACAS#14]
Hi team,
The online file [https://gitlab.unil.ch/carmona/STACAS.demo/blob/master/aux/cellCycle.symbol.DE.specific.170120.csv](url) mentioned at the STACAS tutorial page ([https://carmonalab.github.io/STACAS.demo/tutorial.html](url)) is not accessible along with this GitLab Repo link [https://gitlab.unil.ch/groups/carmona](url) mentioned at [https://carmonalab.github.io/](url). How could I get that csv file?
Thanks
DUAN

**Comment by mass-a** [comment]
Hello Duan,
here's a working [LINK](https://github.com/carmonalab/STACAS.demo/blob/master/aux/cellCycle.symbol.DE.specific.170120.csv) to the cell cycling signature. The [STACAS demo](https://carmonalab.github.io/STACAS.demo/tutorial.html) was also updated with the correct link.

Thanks for reporting this!
