### ISSUE TITLE
Process bar?

### ISSUE THREAD

**Issue by MingwuDuan** [carmonalab/STACAS#15]
Hi team,
I used FindAnchors.STACAS() to handle my 48 sample matrices (over 120,000 cells) and after receiving this message
> Finding neighborhoods
Finding anchors
        Found 233 anchors
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=56m 57s

I found no success or error output message on the dashboard for a very very long time so that I terminated the "crashed" procedure several times although the task manager showed CPU was still running.

**Comment by MingwuDuan** [comment]
I have read source code and guess the solution is as below:
When FindIntegrationAnchors.wdist() has returned ref.anchors object, the last two key columns of the data frame ref.anchors@anchors should be exacted and then transformed into matrix with correct colnames, subsequently corresponding functions should be applied over matrix row, e.g. 
`MatrixRowMean<-apply(thisMatrix,1,mean)
MatrixRowMax <-apply(thisMatrix,1,max)
MatrixRowMin <-apply(thisMatrix,1,min)`
This makes much much faster due to reduced ref.anchors@anchors read and write operations, and finally to integrate ref.anchors@anchors and these apply() results.

**Comment by mass-a** [comment]
Well spotted!

you are right, there is slow `for` loop that should have been better written as an `apply()` call. This was changed in the development version and will be available in the next STACAS release.

Thanks!
-m
