### ISSUE TITLE
Seurat Normalization

### ISSUE THREAD

**Issue by kvittingseerup** [carmonalab/STACAS#2]
Thanks for the nice tutorials. In there you use NormalizeData(). Do you have experience with using SCTransform() instead as suggested int the SCTransform workflow [here](https://satijalab.org/seurat/v3.2/integration.html) which privides "improved pre-processing and normalization"?

**Comment by mass-a** [comment]
Hello Kristoffer,
thanks for the post.

In version 1.0 of STACAS we opted for a standard log-transformation to normalize the data, which is very simple and works well in our hands. It is true that in some cases (e.g. when there is a large heterogeneity in sequencing depth) the SCTransform may be beneficial. We may add the SCT normalization in the next update to the method, but haven't implemented this yet!

**Comment by kvittingseerup** [comment]
Is STACAS doing normalisation within the functions? I was just refering to the tourial where I can just replace  NormalizeData() with SCTransform() - or will that break something?

**Comment by mass-a** [comment]
Well, it's a bit more complicated than that.

The SCT requires a slightly different workflow than the regular normalization, e.g. (following the tutorial in the link you provided) you need to run `PrepSCTIntegration` and then pass on *normalization.method = "SCT"* to the function `FindIntegrationAnchors`. We have not implemented this part in our anchor-finding function. It's on our to-do list, though.

**Comment by mass-a** [comment]
We have added support for SCTransform in the latest update (v1.1.0).

Here's some sample code that can be used to apply SCT prior to integration:
```
ref.list <- SplitObject(data, split.by = "sample")
ref.list <- lapply(ref.list, FUN = SCTransform, variable.features.n = 800)
features.sct <- SelectIntegrationFeatures(ref.list, nfeatures = 500)
ref.list <- PrepSCTIntegration(ref.list, anchor.features = features.sct)
ref.list <- lapply(ref.list, FUN = RunPCA, features = features.sct)
```
Then use STACAS on the SCT assay:
```
anchors.sct <- FindAnchors.STACAS(ref.list, anchor.features=features.sct, 
                               normalization.method = "SCT")
anchors.sct.filtered <- FilterAnchors.STACAS(anchors.sct)
mySampleTree <- SampleTree.STACAS(anchors.sct.filtered)
```
And finally integrate with Seurat and the filtered anchor set:
```
ref.integrated.sct <- IntegrateData(anchorset=anchors.sct.filtered, dims=1:10, k.weight=50,
                       normalization.method = "SCT", sample.tree=mySampleTree, preserve.order=T)
```
