### ISSUE TITLE
How to tune the STACAS guide tree

### ISSUE THREAD

**Issue by lucygarner** [carmonalab/STACAS#20]
Hi,

How do I go about tuning the STACAS guide tree? I couldn't see instructions for this here: https://carmonalab.github.io/STACAS.demo/STACAS.demo.html#stacas-integration-guide-trees. And how would I decide on the best order for integration? I am correcting for "donor".

Best wishes,
Lucy

**Comment by mass-a** [comment]
Hello Lucy,

the `SampleTree.STACAS` function calculates integration trees based on the sum of the integration anchor weights between pairs of datasets. The idea is to start integration from the most "centroid" datasets, i.e. those with the largest sum of anchor weights with the remaining data sets.  Based on the pairwise distance matrix, the actual integration order is decided by hierarchical clustering; you can change the clustering method in STACAS with the `hclust.method` parameter, which can be any method accepted by [hclust](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/hclust.html).

If you are not happy with the automatically generated integration trees, you can specify your custom trees using the format of Seurat's sample.tree objects. e.g. as described [HERE](https://satijalab.org/seurat/reference/integratedata). 
 
Best
-massimo
