### ISSUE TITLE
Preparing PCA embeddings for objects...  1/5 2/5 3/5 4/5 5/5 Finding integration anchors... Error in Embeddings(object = object.list[[x]][[nn.reduction]])[, dims] :    subscript out of bounds

### ISSUE THREAD

**Issue by AlonsoOga** [carmonalab/STACAS#21]
Hi, 

I am integrating datasets from 4 distantly related species. We thought STACAS would be a great fit for our purposes as we want to keep the biological differences across datasets and default Seurat seems too harsh on it. However, when running the `FindAnchors.STACAS` function, I am unable to return the anchor object and I get the Embeddings error. I initially thought it was because I am having datasets with different genes, but after subsetting the data to keep only the genes that are shared across all 4 datasets, I am still getting this error. 

In my pipeline I am grabbing the raw counts from each dataset, merging them and running the default Seurat pipeline with `FindVariableFeatures %>% NormalizeData() %>% ScaleData() %>% RunPCA() %>% RunUMAP() %>%` and then splitting this merged object in a list object split by dataset (I am not using the SCT assay since it seems STACAS is not yet able to handle them). After this, I run `stacas_anchors <- FindAnchors.STACAS(comb.list, anchor.features = ngenes, dims = 1:nDims)`, where ngenes = 5000 and the same VariableGenes calculated and nDims = 80 and the same ndims that were used for RunPCA and RunUMAP... How can I circumvent this problem?

**Comment by mass-a** [comment]
Hello Alonso,
sorry we didn't respond earlier.

Perhaps you have fewer than 5000 genes left after subsetting on shared genes between the species? Have you tried to run this integration on lower dimensionality, e.g. lowering to 1000 variable genes and 10 PCAs, to see if the error persists?

-m
