### ISSUE TITLE
Error when running STACAS on spatial data

### ISSUE THREAD

**Issue by kokonech** [carmonalab/STACAS#22]
Hi! I am tying to use STACAS on the spatial snRNA-seq data. The following error occurs:

```
> Run.STACAS(ob.list)
Run.STACAS(ob.list)
94.8 % of genes found across all datasets
Error in FindVariableFeatures.STACAS(x, nfeat = n.this, genesBlockList = genesBlockList) :
  trying to get slot "var.features" from an object of a basic class ("NULL") with no slots
```

Is it connected somehow to low amount of genes in the protocol (n=100)? Or something with Seurat version incompatibilty? The following versions are used: STACAS_2.0.5,  Seurat_4.3.0 , R 4.2.2

**Comment by kokonech** [comment]
Hi , created from list of processed Seurat objects, here's the code:

```
ob.list <- list()
orig.ids <- c()
for (sId in sIds) {
    sPath = paste0(dataDir,sId,".res.rds")
    print(sId)
    ob.list[[sId]] <- readRDS(sPath)
    orig.ids <- c(orig.ids,rep(sId,ncol(ob.list[[sId]])))
}

Run.STACAS(ob.list)
```

But for Seurat objects I did not compute variable genes since all genes were used for clustering, UMAP, etc. Could this be the issue? Is there a way to pre-assign this?

**Comment by kokonech** [comment]
Thanks for the reply, I used the genes present in each sample (intersect), the analysis worked well, currently inspecting the result. However small issue occred. There were several warnings like this:

```
Warning in irlba(A = t(x = object), nv = npcs, ...) :
  You're computing too large a percentage of total singular values, use a standard svd instead.
```
Should be this handled somehow via params?

Also, is there a way to find the markers of new clusters? FindAllMarkers() function did not work properly.

**Comment by mass-a** [comment]
Good that it worked.

As for the warning, it should be fine to ignore it, see https://github.com/satijalab/seurat/issues/1249 . You may also try to lower the number of PCs, since the dimensionality of your data is already quite low (use the parameter `dims` in STACAS).

I am not sure why FindAllMarkers() would fail, but perhaps try to re-normalize the original data before running the function. For example:
```r
DefaultAssay(integrated) <- 'RNA'
integrated <- NormalizeData(integrated)
markers <- FindAllMarkers(integrated)
```

**Comment by kokonech** [comment]
Great,  everything worked, thanks for replies, closing the issue.
