### ISSUE TITLE
Error while finding anchors with semi supervised approach

### ISSUE THREAD

**Issue by daymecita** [carmonalab/STACAS#24]
Hello!

Thans a lot for releasing this new method. It looks promising, and I have been trying to test it with my datasets that have in total more than 500 K cells. As you did with the CD8 human atlas T cells, I used the 20 biggest datasets as a reference. However, when finding anchors between the integrated reference and the rest of the datasets, I obtained this error: 
Error in flag[anchors$Consistent == FALSE] <- accept : 
  NAs are not allowed in subscripted assignments
Calls: FindAnchors.STACAS -> inconsistent_anchors -> probabilistic_reject
Execution halted

Do you know why? Do you think is that in some of my datasets I might not have all cell types I am using in the cell.labels argument? 
Thanks!
Dayme

**Comment by mass-a** [comment]
Hello Dayme,
thanks for reporting this.

Is it a particular sample that is failing to integrate, or multiple ones? anything particular about this sample(s), e.g. low number of cells, only one cell type present, ...? and about the metadata column with the cell type labels, does it contain NA, NULL, or special characters in the samples that give an error? this would help narrowing down the source of the error. Also please report the list of commands you are using to run STACAS.

Thanks,
-m

**Comment by daymecita** [comment]
Hi thanks for your quick response :)
I don't know which sample is failing since the log files only say "Finding anchors between all query and reference datasets", and then it starts finding neighborhoods and anchors for a long time until it fails. 
I am using this command:
stacas_anchors <- FindAnchors.STACAS(scData.list,
                                     reference = 1,
                                     cell.labels = 'CellID_l1',
                                     anchor.features = hvg,
                                     dims = 1:npcs)
All datasets have been annotated already with the labels: Mast_cells, Stromal, Myeloid , T.NK_cells, Endothelial, and B_cells.  For some samples I have 0 or very few cells (even 1) for some CellID_l1 value, (i.e. Bcells). Do you think that is what is causing the issue? Should all samples have a certain number of cells per cell label? 

Thanks!

**Comment by mass-a** [comment]
It's totally fine to have whole cell types absent from some samples. Integration should work as long as there is at least one cell type in common between any pair of datasets (in your case, at least one cell type in common between query and reference datasets). It's also possible to leave a fraction of cells as unlabeled, by setting their cell type label to NA.

I could not reproduce your error on my machine. But I added a few extra checks that should prevent the NA subscripts that may have triggered the error; can you try to install the development version and see if the problem persists?

```r
remotes::install_github("carmonalab/STACAS", ref="dev")
```

**Comment by daymecita** [comment]
Hi Mass, it worked after installing the dev version. 

Thanks :)
