### ISSUE TITLE
Finding markers after integration

### ISSUE THREAD

**Issue by vercanie** [carmonalab/STACAS#26]
Dear team,
Thanks for developing a great package! After the last update, I cannot find any markers with FindMarkers / FindAllMarkers on the integrated object. I'm getting the following warning message:

```
“When testing 0 versus all:
	normalization.method is not a valid parameter for FindIntegrationAnchors.wdist”
```

Here's a reproducible workflow that generates the issue. 

```
library(SeuratData)
InstallData("cbmc")
InstallData("pbmc3k")
pbmc  <- SeuratData::LoadData(ds = "pbmc3k")
cbmc  <- SeuratData::LoadData(ds = "cbmc")
merged.list  <- list(pbmc, cbmc)

merged.list <- lapply(X = merged.list, FUN = function(x) {
    DefaultAssay(x)  <- "RNA"
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, nfeatures = 2000)
})

integrated_object <- Run.STACAS(merged.list, dims = 1:12)
integrated_object <- RunUMAP(integrated_object, dims = 1:12) 
integrated_object  <- FindNeighbors(integrated_object)
integrated_object  <- FindClusters(integrated_object, res = 0.1)

mrk  <- FindAllMarkers(integrated_object)
```

Thanks a lot for your help!
 Best, 
Veronika

**Comment by mass-a** [comment]
Hello Veronika,
thanks for reporting.
I have tested your code with R_4.3.0, Seurat_4.3.0.1, STACAS_2.1.3 and it runs without error. Can you tell me which versions of R, Seurat and STACAS you are using?

**Comment by vercanie** [comment]
Hi! Thanks for the quick reply. I was running it with R_4.2.1, Seurat_4.3.0, STACAS_2.0.1. After updating STACAS and a few related packages, everything runs fine. Once again, thank you a lot for your help and for the development and maintenance of a wonderful package!
