### ISSUE TITLE
Integration error (due to small number of cells?)

### ISSUE THREAD

**Issue by kvittingseerup** [carmonalab/STACAS#3]
I've been trying to integrate some single cell RNAseq datasets (where the smallest is 544 cells) following the [3rd toturial](https://carmonalab.github.io/STACAS/tutorial.html) but when I run `IntegrateData` i get the following error:

```
Integrating data
Merging dataset 15 into 5
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
Error in nn2(data = c(5.73634646392675, -24.8149986124873, -6.20325662067301,  :
                     Cannot find more nearest neighbours than there are points
```

When googleling the error I mainly find refrences to [this](https://github.com/satijalab/seurat/issues/997) where they suggest to use the `k.filter` argument of `Seurat::FindIntegrationAnchors()`.

What is the equivalent filtering step when using the STACAS approach?

Cheers
Kristoffer

**Comment by mass-a** [comment]
My guess would be that, in your example, either dataset 15 or 5 didn't have enough anchors for integration after anchor filtering. You could check that by:
```
table(ref.anchors.filtered@anchors[,c("dataset1","dataset2")])
```

What is the output of `PlotAnchors.STACAS`, do you have any distribution that falls entirely to the right of the automatic threshold? STACAS tries to guess a threshold on the anchor score to filter out bad anchors, but it may not work in all instances (especially if you had very few cells to start with). If that is the case, you could set manually a higher threshold to the `FilterAnchors.STACAS` function using the `dist.thr` parameter.

**Comment by kvittingseerup** [comment]
I think you are right about the filtering. Could you elaborate on where the treshold is supposed to be compared to the distributions of my data?

**Comment by mass-a** [comment]
You can guide your choice for the threshold parameter by looking at the anchor distance distributions produced by `PlotAnchors.STACAS`. If you choose a high `dist.thr` (i.e. all the way to the right of the distance distributions), no anchors will be filtered out and you may see over-correction of batch effects. As you lower `dist.thr` you should see a milder correction of batch effects, until it becomes to small and it filters out too many anchors to perform integration. Therefore the `dist.thr` is a handle on the amount of batch-effect (over)correction that you want to apply to the integration task.

The "right" value for this parameter will depend on the specifics of your data, and whether you have some ground truth to evaluate the quality of the integration. For instance, in our [integration tutorial](https://carmonalab.github.io/STACAS/tutorial.html) we had information about whether the individual datasets were composed of CD4+ or CD8+ cells, and we could evaluate somewhat the quality of the integration by checking whether CD4+ and CD8+ cells were aligned to each other, which would likely imply batch-effect over-correction.

**Comment by kvittingseerup** [comment]
Thanks for the clarification. Guess this means that from a practical point of view I the filtering needs to ensure that:

```
summary(as.dist( table(ref.anchors.filtered@anchors[,c("dataset1","dataset2")]) ))
```

Does not contain to many (any?) zeroes?

Cheers
Kristoffer

**Comment by mass-a** [comment]
Yes, something like that!

**Comment by kvittingseerup** [comment]
Thanks for the help :-)
