### ISSUE TITLE
CheckGC() not imported from SeuratObject

### ISSUE THREAD

**Issue by gdagstn** [carmonalab/STACAS#31]
Hi Massimo,

this is a quick issue I ran into when calling `Run.STACAS()` from within a function when `Seurat` is not loaded in the namespace. 

It's easily overcome by loading `SeuratObject`, but I thought you may want to consider importing it?

Thanks!

**Comment by mass-a** [comment]
Thanks Giuseppe!

I'm applying some patches to the code as we speak, so I will also add the missing import you reported.

Best
-m
