### ISSUE TITLE
seurat v3

### ISSUE THREAD

**Issue by alexthiery** [carmonalab/STACAS#5]
Hi, is the previous STACAS version compatible with seurat v3 is still available to install, or has this been deprecated? Thanks!

**Comment by mass-a** [comment]
Hello Alex,

yes, you should still be able to install older versions by specifying the tag or the commit ID. For the most recent stable version (1.0.1) compatible with Seurat 3 you can do: 
```
remotes::install_github("carmonalab/STACAS", ref="1.0.1")
```

Cheers!
