### ISSUE TITLE
Can I run STACAS on Seurat 4?

### ISSUE THREAD

**Issue by jig4003** [carmonalab/STACAS#6]
I have recently installed the latest Seurat 4. Is it recommended to run STACAS on Seurat 4 or I should stick to Seruat3?
Thanks

**Comment by mass-a** [comment]
Seurat v4 has several new features for multimodal analysis, but the dataset integration functionalities are essentially unchanged from previous versions. So you should see nearly identical results by running STACAS on Seurat v3 or v4.
