### ISSUE TITLE
Cholmod error 'problem too large'

### ISSUE THREAD

**Issue by LauRich05** [carmonalab/STACAS#8]
Hi there, 

I am trying to run STACAS integration on a dataset comprised of ~270,000 cells from 52 samples. I keep running into the error below on the IntegrateData() step. Seurat forums recommend using their new "rpca" integration method to overcome this - but it hasn't performed as well as STACAS on my dataset, and I'm not sure how RPCA would integrate into the STACAS workflow. Do you have any workarounds to overcome this error on large datasets? I am running 

Error in .cbind2Csp(x, y) : Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 89 Calls: ... cbind -> cbind2 -> cbind2 -> cbind2sparse -> .cbind2Csp Execution halted

**Comment by mass-a** [comment]
Hello Laura and thanks for the report.

It looks like your machine is running out of memory on this large dataset - how much RAM do you have?

You could try to downsample your dataset to reduce the number of cells (e.g. see https://github.com/satijalab/seurat/issues/1325), which could even help balancing out samples of very different sizes. But if you want to use all cells for integration, you may have to run the integration step on a machine with more RAM.

STACAS actually uses reciprocal PCA for integration, so I don't expect 'rpca' would be a solution.

Best,
-m
